name: CI Pipeline

on:
  push:
      branches: [ "main" ]

jobs:
    build:
        runs-on: ubantu-latest

        steps:
           - name: Checkout code
             uses: actions/checkout@v4
   
           - name: Set up Python
             uses: actions/setup-python@v5
             with:
                 python-version: '3.11'

           - name: Install dependencies
             run: pip install flask
 
           - name: Run simple check
             run: python -c "import flask; print('Flask installed successfully')" 
